
version: '3'

services:
  nginx-service:
    image: eleott/nginx_service:dev0ps7
    # build: ./nginx
    ports:
      - 8081:8081
      - 8087:8087

  rabbitmq-service:
    image: eleott/rabbitmq_service:dev0ps7
      
  postgres-service:
    image: eleott/postgres_service:dev0ps7   
    # build: ./services/database
  
  booking-service:
    image: eleott/booking_service:dev0ps7
    # build: ./services/booking-service
  
  hotel-service:
    image: eleott/hotel_service:dev0ps7
    # build: ./services/hotel-service
      
  loyalty-service:
    image: eleott/loyalty_service:dev0ps7
    # build: ./services/loyalty-service
        
  payment-service:
    image: eleott/payment_service:dev0ps7
    # build: ./services/payment-service
    
  report-service:
    image: eleott/report_service:dev0ps7
    # build: ./services/report-service
    
  session-service:
    image: eleott/session_service:dev0ps7
    # build: ./services/session-service
    # ports:
      # - 8081:8081
  
  gateway-service:
    image: eleott/gateway_service:dev0ps7
    # build: ./services/gateway-service
    # ports:
      # - 8087:8087
